version: 0.0
os: linux
files:
  - source: /scripts/deploy_docker.sh
    destination: /home/ec2-user/scripts/

hooks:
  AfterInstall:
    - location: /home/ec2-user/scripts/deploy_docker.sh
      timeout: 300
      runas: ec2-user
